{% set name = "taospy" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbd4ee918f80df3a533c29f4ba70cdfa476bca8e3ddd6ef0ce6ff61fdb809de9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - poetry-core
    - requests
  run:
    - python
    - iso8601
    - pytz
    - requests

test:
  imports:
    - taosrest

about:
  home: http://tdengine.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TDengine connector for python
  doc_url: https://docs.taosdata.com/reference/connector/python
  dev_url: https://github.com/taosdata/taos-connector-python/

extra:
  recipe-maintainers:
    - zitsen
