{% set name = "taospy" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 894407b9608759cf21bfcc26445446dc78db9cf45a36ff238b3d77e5a91cc6e2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - poetry-core
    - requests
  run:
    - python
    - iso8601
    - pytz
    - requests

test:
  imports:
    - taosrest

about:
  home: http://tdengine.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TDengine connector for python
  doc_url: https://docs.taosdata.com/reference/connector/python
  dev_url: https://github.com/taosdata/taos-connector-python/

extra:
  recipe-maintainers:
    - zitsen
