{% set name = "taospy" %}
{% set version = "2.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08642312874b44bc49ae5fd2b802334063e5bcf779f7edc0ab07f3bbb80d789e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - poetry-core
    - requests
  run:
    - python
    - iso8601
    - pytz
    - requests

test:
  imports:
    - taosrest

about:
  home: http://tdengine.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TDengine connector for python
  doc_url: https://docs.taosdata.com/reference/connector/python
  dev_url: https://github.com/taosdata/taos-connector-python/

extra:
  recipe-maintainers:
    - zitsen
